#!/usr/bin/env python3
"""One-click academic tally deploy utility.

Reads structured tally data and writes:
- academic_tally.deployed.json
- academic_tally_report.md
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Dict, Any


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Deploy academic tally artifacts")
    parser.add_argument(
        "--input",
        default="data/academic_tally.json",
        help="Path to the source tally JSON file",
    )
    parser.add_argument(
        "--output-dir",
        default="artifacts/academic",
        help="Directory where generated outputs are written",
    )
    return parser.parse_args()


def render_markdown(data: Dict[str, Any]) -> str:
    tally = data["academic_tally"]
    totals = data["total_counts"]

    header = "| Alias / Pseudonym | Doctrines | Theses | Hypotheses | PhD-Level Works | Total |"
    separator = "|---|---:|---:|---:|---:|---:|"

    rows = []
    for alias, works in tally.items():
        total = works["Doctrines"] + works["Theses"] + works["Hypotheses"] + works["PhD"]
        rows.append(
            f"| {alias} | {works['Doctrines']} | {works['Theses']} | {works['Hypotheses']} | {works['PhD']} | {total} |"
        )

    rows.append(
        f"| **Total** | **{totals['Doctrines']}** | **{totals['Theses']}** | **{totals['Hypotheses']}** | **{totals['PhD-Level Works']}** | **{totals['Total']}** |"
    )

    return "\n".join(
        [
            "# Combined Academic Tally",
            "",
            f"Source: {data.get('source', 'n/a')}",
            "",
            header,
            separator,
            *rows,
            "",
            "## Notes",
            "- Generated by `tools/deploy_academic_tally.py`.",
            "- Use this report for quick reference and Codex-side integrations.",
        ]
    )


def main() -> None:
    args = parse_args()
    input_path = Path(args.input)
    out_dir = Path(args.output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    with input_path.open("r", encoding="utf-8") as f:
        data = json.load(f)

    deployed_json = out_dir / "academic_tally.deployed.json"
    report_md = out_dir / "academic_tally_report.md"

    with deployed_json.open("w", encoding="utf-8") as f:
        json.dump(data, f, indent=2)
        f.write("\n")

    report_md.write_text(render_markdown(data), encoding="utf-8")

    print(f"Wrote: {deployed_json}")
    print(f"Wrote: {report_md}")


if __name__ == "__main__":
    main()
